# Generated by Django 4.1.3 on 2023-02-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_newuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='avatar',
            field=models.ImageField(blank=True, default=None, max_length=500, null=True, upload_to='users'),
        ),
    ]
