# Generated by Django 4.1.3 on 2023-02-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_newuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='avatar',
            field=models.ImageField(default='users/user.png', max_length=500, upload_to='users'),
        ),
    ]
