# Generated by Django 4.1.3 on 2023-02-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_newuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='avatar',
            field=models.ImageField(default='users/user.png', upload_to='users'),
        ),
    ]
