# Generated by Django 4.1.3 on 2023-02-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('updated',)},
        ),
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ('updated',)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['updated', 'created']},
        ),
    ]
