# Generated by Django 4.1.3 on 2023-02-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='pages',
            field=models.ManyToManyField(blank=True, related_name='page', to='Comics.page'),
        ),
    ]
