# Generated by Django 4.1.3 on 2023-02-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='genres',
        ),
        migrations.AddField(
            model_name='comic',
            name='category',
            field=models.ManyToManyField(to='Comics.categorys'),
        ),
        migrations.AddField(
            model_name='comic',
            name='genres',
            field=models.ManyToManyField(to='Comics.genre'),
        ),
    ]
