# Generated by Django 4.1.3 on 2023-02-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='images',
        ),
    ]
