# Generated by Django 4.1.3 on 2023-02-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0002_alter_chapter_options_alter_comic_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='like_count',
            field=models.BigIntegerField(blank=True),
        ),
    ]
