# Generated by Django 4.1.3 on 2023-02-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='image_urls',
            field=models.URLField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='image_urls',
            field=models.URLField(max_length=100000, null=True),
        ),
    ]
