# Generated by Django 4.1.3 on 2023-02-19 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0002_remove_comic_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comic',
            old_name='image_urls',
            new_name='image',
        ),
    ]
