# Generated by Django 4.1.3 on 2023-02-15 04:36

import Comics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0003_alter_comic_image_urls_alter_page_image_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='images',
            field=models.ImageField(max_length=100000, null=True, upload_to=Comics.models.comics_images_location),
        ),
        migrations.AlterField(
            model_name='page',
            name='images',
            field=models.ImageField(blank=True, max_length=100000, null=True, upload_to=Comics.models.comics_chapters_images_location),
        ),
    ]
