# Generated by Django 4.1.3 on 2023-02-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0003_alter_comic_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='like_count',
            field=models.IntegerField(blank=True),
        ),
    ]
