# Generated by Django 4.1.3 on 2023-02-15 05:18

import Comics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0004_alter_comic_images_alter_page_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='image_urls',
            field=models.URLField(max_length=100000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='images',
            field=models.ImageField(blank=True, max_length=100000, null=True, upload_to=Comics.models.comics_images_location, verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image_urls',
            field=models.URLField(max_length=100000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='images',
            field=models.ImageField(blank=True, max_length=100000, null=True, upload_to=Comics.models.comics_chapters_images_location, verbose_name='Images'),
        ),
    ]
