# Generated by Django 4.1.3 on 2023-02-14 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0004_alter_chapter_pages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ('updated', 'created', 'title')},
        ),
    ]
